#!/bin/bash

## Description: Change files for next tag
## Usage: next

current_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
IFS='.' read -r -a version_parts <<< "$current_tag"
new_tag="${version_parts[0]}.${version_parts[1]}.$((version_parts[2] + 1))"
sed -i '' -E "s/[0-9]+\.[0-9]+\.[0-9]+/$new_tag/g" ci/provider/gitlab/main.yml

echo "Tag: $new_tag"

