.build_backend_before_script:
  script: []

.build_backend_script_start:
  script: []

.build_backend_script_end:
  script: []

build-backend:
  stage: build
  needs:
    - job: init
  image:
    name: $BACKEND_IMAGE
  retry:
    max: 2
  before_script:
    - !reference [.build_backend_before_script, script]
    - if [ -n "$BUILD_BACKEND_BEFORE_SCRIPT" ]; then eval "$BUILD_BACKEND_BEFORE_SCRIPT"; fi
  script:
    - !reference [.build_backend_script_start, script]
    - if [ -n "$BUILD_BACKEND_SCRIPT_START" ]; then eval "$BUILD_BACKEND_SCRIPT_START"; fi
    - bash -c "$BACKEND_COMMAND_BUILD"
    - if [ -n "$BUILD_BACKEND_SCRIPT_END" ]; then eval "$BUILD_BACKEND_SCRIPT_END"; fi
    - !reference [.build_backend_script_end, script]
  artifacts:
    paths:
      - $BACKEND_FOLDER_BUILD_1
      - $BACKEND_FOLDER_BUILD_2
      - $BACKEND_FOLDER_BUILD_3
      - $BACKEND_FOLDER_BUILD_4
      - $BACKEND_FOLDER_BUILD_5
    exclude:
      - $BACKEND_FOLDER_BUILD_EXCLUDE_1
      - $BACKEND_FOLDER_BUILD_EXCLUDE_2
      - $BACKEND_FOLDER_BUILD_EXCLUDE_3
      - $BACKEND_FOLDER_BUILD_EXCLUDE_4
      - $BACKEND_FOLDER_BUILD_EXCLUDE_5
    expire_in: 120 min
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH =~ $DEPLOY_TRIGGER_BY_CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ $DEPLOY_TRIGGER_BY_CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "trigger" && $ACTION == "deploy"
    - if: $CI_PIPELINE_SOURCE == "web" && $ACTION == "deploy"