.build_frontend_before_script:
  script: []

.build_frontend_script_start:
  script: []

.build_frontend_script_end:
  script: []

build-frontend:
  stage: build
  needs:
    - job: init
  image:
    name: $FRONTEND_IMAGE
  retry:
    max: 2
  before_script:
    - !reference [.build_frontend_before_script, script]
    - if [ -n "$BUILD_FRONTEND_BEFORE_SCRIPT" ]; then eval "$BUILD_FRONTEND_BEFORE_SCRIPT"; fi
  script:
    - !reference [.build_frontend_script_start, script]
    - if [ -n "$BUILD_FRONTEND_SCRIPT_START" ]; then eval "$BUILD_FRONTEND_SCRIPT_START"; fi
    - bash -c "$FRONTEND_COMMAND_BUILD"
    - if [ -n "$BUILD_FRONTEND_SCRIPT_END" ]; then eval "$BUILD_FRONTEND_SCRIPT_END"; fi
    - !reference [.build_frontend_script_end, script]
  artifacts:
    paths:
      - $FRONTEND_FOLDER_BUILD_1
      - $FRONTEND_FOLDER_BUILD_2
      - $FRONTEND_FOLDER_BUILD_3
      - $FRONTEND_FOLDER_BUILD_4
      - $FRONTEND_FOLDER_BUILD_5
    expire_in: 120 min
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH =~ $DEPLOY_TRIGGER_BY_CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ $DEPLOY_TRIGGER_BY_CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "trigger" && $ACTION == "deploy"
    - if: $CI_PIPELINE_SOURCE == "web" && $ACTION == "deploy"